/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  EthereumConfig,
  EthereumConfigInterface,
} from "../../../../../@fhevm/solidity/config/ZamaConfig.sol/EthereumConfig";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "protocolId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60806040523461013357466001036100885761001961016a565b505f6040610025610137565b8281526020810183905201525f5160206102a05f395f51905f5280546001600160a01b03199081169091555f5160206102605f395f51905f528054821690555f5160206102805f395f51905f52805490911690555b604051607c90816101e48239f35b4662aa36a70361011f5761011a61009d610184565b80515f5160206102a05f395f51905f5280546001600160a01b039283166001600160a01b03199182161790915560208301515f5160206102605f395f51905f528054919093169116179055604001515f5160206102805f395f51905f5280546001600160a01b0319166001600160a01b0392909216919091179055565b61007a565b617a69460361007a5761011a61009d610184565b5f80fd5b60405190606082016001600160401b0381118382101761015657604052565b634e487b7160e01b5f52604160045260245ffd5b610172610137565b905f82525f60208301525f6040830152565b61018c61016a565b50610195610137565b73f0ffdc93b7e186bc2f8cb3daa75d86d1930a433d81527392c920834ec8941d2c77d188936e1f7a6f49c127602082015273be0e383937d564d7ff0bc3b46c51f0bf8d5c311a60408201529056fe60808060405260043610156011575f80fd5b5f3560e01c63da1f12ab146023575f80fd5b34603e575f366003190112603e57602090603a6042565b8152f35b5f80fd5b46600103604e57600190565b4662aa36a703605d5761271190565b617a6946146069575f90565b6127119056fea164736f6c634300081b000a9e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e46497019e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e46497029e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e4649700";

type EthereumConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EthereumConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EthereumConfig__factory extends ContractFactory {
  constructor(...args: EthereumConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EthereumConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): EthereumConfig__factory {
    return super.connect(runner) as EthereumConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EthereumConfigInterface {
    return new Interface(_abi) as EthereumConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EthereumConfig {
    return new Contract(address, _abi, runner) as unknown as EthereumConfig;
  }
}
