/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PrivateMsg {
  export type MSGStruct = {
    from: AddressLike;
    to: AddressLike;
    msgContent: BytesLike;
    time: BigNumberish;
  };

  export type MSGStructOutput = [
    from: string,
    to: string,
    msgContent: string,
    time: bigint
  ] & { from: string; to: string; msgContent: string; time: bigint };

  export type MSGListStruct = {
    privateKey: BytesLike;
    dialogueAddress: AddressLike;
    from: AddressLike;
    to: AddressLike;
    msgList: PrivateMsg.MSGStruct[];
  };

  export type MSGListStructOutput = [
    privateKey: string,
    dialogueAddress: string,
    from: string,
    to: string,
    msgList: PrivateMsg.MSGStructOutput[]
  ] & {
    privateKey: string;
    dialogueAddress: string;
    from: string;
    to: string;
    msgList: PrivateMsg.MSGStructOutput[];
  };
}

export interface PrivateMsgInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dialogue"
      | "dialoguePrivateKeys"
      | "getMsgDetail"
      | "getMsgID"
      | "getMsgList"
      | "getUser"
      | "protocolId"
      | "register"
      | "sendMsg"
      | "userMsg"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "dialogue",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dialoguePrivateKeys",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMsgDetail",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMsgID",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMsgList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMsg",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userMsg",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "dialogue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dialoguePrivateKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMsgDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMsgID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMsgList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sendMsg", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userMsg", data: BytesLike): Result;
}

export interface PrivateMsg extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateMsg;
  waitForDeployment(): Promise<this>;

  interface: PrivateMsgInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dialogue: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        from: string;
        to: string;
        msgContent: string;
        time: bigint;
      }
    ],
    "view"
  >;

  dialoguePrivateKeys: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  getMsgDetail: TypedContractMethod<
    [dialogueAddresses: AddressLike],
    [PrivateMsg.MSGListStructOutput],
    "view"
  >;

  getMsgID: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [string],
    "view"
  >;

  getMsgList: TypedContractMethod<
    [user: AddressLike],
    [PrivateMsg.MSGListStructOutput[]],
    "view"
  >;

  getUser: TypedContractMethod<[user: AddressLike], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  register: TypedContractMethod<
    [passwordAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  sendMsg: TypedContractMethod<
    [
      to: AddressLike,
      _privateKey: BytesLike,
      msgContent: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  userMsg: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dialogue"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        from: string;
        to: string;
        msgContent: string;
        time: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "dialoguePrivateKeys"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getMsgDetail"
  ): TypedContractMethod<
    [dialogueAddresses: AddressLike],
    [PrivateMsg.MSGListStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMsgID"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMsgList"
  ): TypedContractMethod<
    [user: AddressLike],
    [PrivateMsg.MSGListStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[passwordAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendMsg"
  ): TypedContractMethod<
    [
      to: AddressLike,
      _privateKey: BytesLike,
      msgContent: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userMsg"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  filters: {};
}
